### ISSUE TITLE
node@6 no longer available via Homebrew

### ISSUE THREAD

**Issue by WaxCylinderRevival** [HistoryAtState/hsg-project#48]
The HSG environment currently utilizes node@6, but node@6 is no longer available via Homebrew. The available versions are node@8 and node@10 [see [https://formulae.brew.sh/formula/node](https://formulae.brew.sh/formula/node)].

As a result, users newly establishing an HSG environment on their local systems will receive a build fail for the "4. Deploy all repositories to localhost" step in the oXygenXML Editor tools menu.

Per @joewiz, if node@8 (or newer) is compatible with hsg-shell, could we migrate to the newer version?

**Comment by joewiz** [comment]
@plutonik-a Could you please check whether we can update to node@8 or newer in our apps that use node, namely, hsg-shell, hsa, and guides? The property files that currently hard code node@6 are:

- https://github.com/HistoryAtState/hsg-shell/blob/master/build.properties
- https://gitlab.com/HistoryAtState/hsa/blob/dev/build.properties
- https://gitlab.com/HistoryAtState/guides/blob/dev/build.properties

Once you have made the necessary updates, I will ensure our setup instructions for installing node dependencies in https://github.com/HistoryAtState/hsg-project/wiki/setup are up to date with the new dependencies.

**Comment by joewiz** [comment]
For additional context, see https://github.com/Homebrew/homebrew-core/pull/39465, which states that `node@6` was removed because it reached its end of life (EOL). `node@8` will reach this same status in December 2019. See https://github.com/nodejs/Release#release-schedule.

**Comment by plutonik-a** [comment]
Status on this issue:  
I have just checked Guides App:   
After updating to node v10.0.0 (which will be supported until 04/2021) the apps and its dependent packages worked fine.  Instead of installing each node version with homebrew I always use (nvm)[https://github.com/nvm-sh/nvm], a node version manager, so it was easy for me to upgrade my node version.   
However, I see a problematic dependency to `bower` packages, whose support will end soon, so looking for alternative npm packages (affects jquery, bootstrap3, bootstrap-less) is needed soon.  
Now I'm going to continue checking HSG-Shell and HSA.

**Comment by plutonik-a** [comment]
Status: 
Check the node 10 update in HSG-Shell (includes update to gulp 4 and general package updates). Instructions are written in the README file.
[https://github.com/HistoryAtState/hsg-shell/pull/340](https://github.com/HistoryAtState/hsg-shell/pull/340)

**Comment by joewiz** [comment]
Closed by https://github.com/HistoryAtState/hsg-shell/pull/340. See https://github.com/HistoryAtState/hsg-project/wiki/setup#updating-from-an-old-setup for updating your HSG Development Environment to work with node@10 as well as the other dependencies that have changed in recent months.
